name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.1
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python deploy.py
